### ISSUE TITLE
QML and canvas

### ISSUE THREAD

**Issue by diam** [barche/QML.jl#10]
Bonjour,

I've tried to run a canvas example from the site [http://www.ics.com/blog/qml-canvas-element](http://www.ics.com/blog/qml-canvas-element) but it doesn't work.
Is it suppose to work?
(The julia script is the same from de QML.jl example)

-- Maurice

<pre>
// Simple example of QML Canvas element
import QtQuick 2.0
// import org.julialang 1.0
Canvas {
    width: 400
    height: 400

    // JuliaContext {
    //   id: julia
    // }

    onPaint: {
        // Get drawing context
        var context = getContext("2d");

        // Make canvas all white
        context.beginPath();
        context.clearRect(0, 0, width, height);
        context.fill();

        // Fill inside with blue, leaving 10 pixel border
        context.beginPath();
        context.fillStyle = "blue"
        context.fillRect(10, 10, width - 20, height - 20);
        context.fill();

        // Draw a line
        context.beginPath();
        context.lineWidth = 2;
        context.moveTo(30, 30);
        context.strokeStyle = "red"
        context.lineTo(width-30, height-30);
        context.stroke();

        // Draw a circle
        context.beginPath();
        context.fillStyle = "orange"
        context.strokeStyle = "red"
        context.moveTo(width/2+60, height/2);
        context.arc(width/2, height/2, 60, 0, 2*Math.PI, true)
        context.fill();
        context.stroke();

        // Draw some text
        context.beginPath();
        context.strokeStyle = "lime green"
        context.font = "20px sans-serif";
        context.text("Hello, world!", width/2, 50);
        context.stroke();
    }
}
</pre>

**Comment by barche** [comment]
Hi,

You need to wrap your QML in an `ApplicationWindow`, see e.g. http://doc.qt.io/qt-5/qqmlapplicationengine.html and http://doc.qt.io/qt-5/qml-qtquick-controls-applicationwindow.html

Be sure to check test/gui.jl, there are some features used there that are not documented yet, such as context properties.

**Comment by ufechner7** [comment]
The following code is working fine for me:
```
// Simple example of QML Canvas element
import QtQuick 2.0
import QtQuick.Controls 1.0
import org.julialang 1.0

ApplicationWindow {
    title: "My Application"
    width: 640
    height: 480
    visible: true

    JuliaContext {
      id: julia
    }

    Canvas {
        width: 400
        height: 400

        onPaint: {
            // Get drawing context
            var context = getContext("2d");

            // Make canvas all white
            context.beginPath();
            context.clearRect(0, 0, width, height);
            context.fill();

            // Fill inside with blue, leaving 10 pixel border
            context.beginPath();
            context.fillStyle = "blue"
            context.fillRect(10, 10, width - 20, height - 20);
            context.fill();

            // Draw a line

            context.beginPath();
            context.lineWidth = 2;
            context.moveTo(30, 30);
            context.strokeStyle = "red"
            context.lineTo(width-30, height-30);
            context.stroke();

            // Draw a circle
            context.beginPath();
            context.fillStyle = "orange"
            context.strokeStyle = "red"
            context.moveTo(width/2+60, height/2);
            context.arc(width/2, height/2, 60, 0, 2*Math.PI, true)
            context.fill();
            context.stroke();

            // Draw some text
            context.beginPath();
            context.strokeStyle = "lime green"
            context.font = "20px sans-serif";
            context.text("Hello, world!", width/2, 50);
            context.stroke();
            }
    }
}
```
@barche : Could you explain, why an ApplicationWindow is needed? Would there be a way to implement the QML wrapper such that it does not need an ApplicationWindow? What would be the advantages and disadvantages?

**Comment by diam** [comment]
@barche and @ufechner7: thank you very much, it works.

I didn't know about the need of `ApplicationWindow`, so yes I have to learn more about QML (or just learn it ;-)!  But I'm now confident that QML is usable with Julia, at least for simple applications.

@ufechner7 If it is the standard way to use canvas with QML why do you want to skip `ApplicationWindow`?
If so, an idee could be to make possible to pass a standard Julia string directly to `QML.QQmlApplicationEngine` instead of a filename (or a QML.QString) so that a glueing method could be written in julia to do that.

Also I see that this code display the canvas in about 5 seconds on my mac, which is less that most julia graphic plotting system. So one can think that your QML wrapper could serve as a basis for other plotting or graph drawing Julia libraries.

-- Maurice

**Comment by barche** [comment]
@diam This is related to the way the QML is loaded. With `QQmlApplicationEngine`, a window is not created, but with `QQuickView` there is. I have added support for `QQuickView`, see test:
`test/qquickview.jl`
To QML from an inline string, a third method using `QQmlComponent` is required, this is also implemented now and demonstrated here:
`test/qqmlcomponent.jl`
Note that this also requires `ApplicationWindow`.

**Comment by diam** [comment]
Thank you very much,
So here is the corrected version of the original example *all in one* Julia file.
The Hello QML message (`qmsg`) come from a Julia string (`julia_msg`).
-- Maurice
<pre>
#!/usr/bin/env julia
using QML

julia_msg = "Hello, world! (from Julia)"

qml_data = QByteArray("""
import QtQuick 2.0
import QtQuick.Controls 1.0
import org.julialang 1.0

ApplicationWindow {
    title: "My Application"
    width: 640
    height: 480
    visible: true

    JuliaContext {
      id: julia
    }

    Canvas {
        width: 400
        height: 400

        onPaint: {
            // Get drawing context
            var context = getContext("2d");

            // Make canvas all white
            context.beginPath();
            context.clearRect(0, 0, width, height);
            context.fill();

            // Fill inside with blue, leaving 10 pixel border
            context.beginPath();
            context.fillStyle = "blue"
            context.fillRect(10, 10, width - 20, height - 20);
            context.fill();

            // Draw a line

            context.beginPath();
            context.lineWidth = 2;
            context.moveTo(30, 30);
            context.strokeStyle = "red"
            context.lineTo(width-30, height-30);
            context.stroke();

            // Draw a circle
            context.beginPath();
            context.fillStyle = "orange"
            context.strokeStyle = "red"
            context.moveTo(width/2+60, height/2);
            context.arc(width/2, height/2, 60, 0, 2*Math.PI, true)
            context.fill();
            context.stroke();

            // Draw some text
            context.beginPath();
            context.strokeStyle = "lime green"
            context.font = "20px sans-serif";
            /// context.text("Hello, world!", width/2, 50);
            context.text(qmsg, 100, 50); // qmsg is set from Julia
            context.stroke();
        }
    }
}
""")

app = QML.application()
qengine = QQmlEngine()
root_ctx = root_context(qengine)
set_context_property(root_ctx, "qmsg", julia_msg)

qcomp = QQmlComponent(qengine)
set_data(qcomp, qml_data, "")
create(qcomp, root_ctx);

# Run the application
QML.exec()
</pre>

**Comment by ufechner7** [comment]
Thanks a lot for the fast progress!
One question: What is the difference between "set_data" and "set_context_property"?
Can "set_data" be used to transfer data from Julia to QML, too?

**Comment by barche** [comment]
Context properties are directly accessible from QML and also notify the GUI when changed. See http://doc.qt.io/qt-5/qqmlcontext.html#details
The `set_data` function only takes QML code as value, see e.g. the first example here: http://doc.qt.io/qt-5/qqmlengine.html#details

**Comment by ufechner7** [comment]
I think, this can be closed now. Can one of you close it, please? I do not have the permission to do it.

**Comment by barche** [comment]
OK, thanks!
