### ISSUE TITLE
JuliaCanvas documentation [suggestion]

### ISSUE THREAD

**Issue by a-ill** [barche/QML.jl#101]
I would suggest to add a line about the importance of setting the environment variable "QSG_RENDER_LOOP" to the documentation of JuliaCanvas.
It took me a couple of hours to figure out why JuliaCanvas was causing an endless loop for my application. I turns out that this happens if one does not include ENV["QSG_RENDER_LOOP"] = "basic" into the julia script. I suppose I am not the last one to make such a mistake.

**Comment by barche** [comment]
Thanks, README is now adjusted!
