### ISSUE TITLE
lrelease in Qt_jll.jl

### ISSUE THREAD

**Issue by clad26** [barche/QML.jl#104]
I am trying to build gnuplot and getting this as an error
```
18:18:51] /workspace/destdir/bin/lrelease qtterminal/po/qtgnuplot_fr.ts -qm qtgnuplot_fr.qm
[18:18:51] make[4]: /workspace/destdir/bin/lrelease: No such file or directory
[18:18:51] make[4]: *** [Makefile:1498: qtgnuplot_fr.qm] Error 127
[18:18:51] make[4]: *** Waiting for unfinished jobs....
```
Which is a part of qtlinguist tools....

**Comment by giordano** [comment]
> It might get resolved if you add lrelease as a build product....

Not really: https://github.com/JuliaPackaging/Yggdrasil/pull/2339#issuecomment-753516952

> it's a binary program, likely built for the target platform, it isn't very useful to us

**Comment by clad26** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/2340

@barche If you've any experience with qmake, can you help here?

**Comment by barche** [comment]
This is not really a QML issue, PR https://github.com/JuliaPackaging/Yggdrasil/pull/2355 should fix it though.
