### ISSUE TITLE
Module "QtCharts" is not installed

### ISSUE THREAD

**Issue by a-ill** [barche/QML.jl#118]
I am getting `module "QtCharts" is not installed` error while using the master branch version. The module does get detected when used form Qt Creator. All other modules seem to work fine.

**Comment by barche** [comment]
Yes, the charts are in a separate package that has no JLL yet, should be fixed when https://github.com/JuliaPackaging/Yggdrasil/pull/2914 is merged, and then you need to also add `using Qt5Charts_jll` on the Julia side.
