### ISSUE TITLE
Improve slot signal handling

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#12]
Please provide a function "connect", that can be used to connect any QML signal with any Julia slot.
Porting the program "FizzBuzz" from the Ruby QML bindings could serve as test case.
See: http://seanchas116.github.io/ruby-qml/

**Comment by barche** [comment]
I have added an example, though it cheats a bit by using context properties. I'll try to update it to send an actual signal from Julia next.

**Comment by barche** [comment]
OK, signals can be emitted now, the readme and FizzBuzz example have been updated. If you want to see how much fun it was to pass arguments from Julia to Qt in a dynamic way, I'll let you marvel at this bit of code:
https://github.com/barche/QML.jl/blob/master/deps/src/qmlwrap/julia_signals.cpp#L13-L85

Ugliest thing I had to write so far :)

In my opinion this completes the basic data transfer mechanisms for QML.jl, see the "Interacting with Julia" section in the readme.

**Comment by ufechner7** [comment]
Thanks a lot! Another milestone is reached. :)
