### ISSUE TITLE
Crash on exit when running Pkg.test("QML")

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#15]
Hello, 

with the newest version of QML.jl I get a crash-on-exit when running the tests on Ubuntu 14.04.

julia> versioninfo()
Julia Version 0.4.5
Commit 2ac304d (2016-03-18 00:58 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY SANDYBRIDGE)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Any idea?

julia> Pkg.test("QML")
INFO: Testing QML
Button was pressed 3 times
Background counter now at 4435
qt_prefix_path() = "/home/ufechner/Qt/5.5/gcc_64"
*** Error in `/usr/bin/julia': free(): invalid pointer: 0x00007f3b9c2d5040 ***

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f3dac802394)
unknown function (ip: 0x7f3dac80e66e)
unknown function (ip: 0x7f3b9adca290)
_ZN3QV413MemoryManager5sweepEb at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN3QV413MemoryManagerD2Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN3QV415ExecutionEngineD1Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN9QV8EngineD1Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN9QV8EngineD0Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN9QJSEngineD1Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN10QQmlEngineD1Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN21QQmlApplicationEngineD0Ev at /home/ufechner/Qt/5.5/gcc_64/lib/libQt5Qml.so.5 (unknown line)
_ZN8cxx_wrap6detail17finalizer_closureI21QQmlApplicationEngineEEP11_jl_value_tS4_PS4_j at /home/ufechner/.julia/v0.4/QML/deps/usr/lib/libqmlwrap.so (unknown line)
unknown function (ip: 0x7f3dacec159f)
unknown function (ip: 0x7f3dacec741c)
jl_atexit_hook at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 0x4016e8)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x401725)
unknown function (ip: (nil))

**Comment by barche** [comment]
Not yet, I get the same on my mac, I was sort of hoping it would only happen on my machine ;)

It seems to me that this only happens when running the tests in sequence, running an individual test and quitting Julia each time (or commenting all but one test from runtests.jl) seems to work without a crash. Can you confirm that it only happens for multiple tests?

**Comment by ufechner7** [comment]
For me, the tests gui.jl and julia_signal.jl always crash on exit, even if one of them is the only test, that is enabled. The other 4 tests work fine, also if they are all enabled at the same time in the runtests.jl file.

**Comment by barche** [comment]
OK, I think it may be fixed now.

**Comment by ufechner7** [comment]
Well, I tested the head version of QML and CxxWrap today, and it is not yet fixed for me. Any idea how to debug this issue?

**Comment by barche** [comment]
Well, if it's still more or less the same trace after the crash (originating in finalizer_closure) I guess it's still an issue with the order-of-finalization. One thing to try is to finalize the engine manually before the app, as I had to do in the plots test:
https://github.com/barche/QML.jl/blob/master/example/plot.jl#L46-L47

**Comment by barche** [comment]
I have rewritten the way the app is created and initialized, leaving the cleanup in C++. Normally, the test suite should now run without crashing. There is also a new mode for running a display in the background for the REPL, see the repl-background.jl example.

I still need to update the docs.

**Comment by ufechner7** [comment]
Seems to be fixed now :)
