### ISSUE TITLE
QML#main precompilation failure

### ISSUE THREAD

**Issue by jheinen** [barche/QML.jl#154]
When I `] add QML#main` in Julia 1.8.5 (on macOS Intel or M1) I get a precompilation error:
```
ERROR: LoadError: UndefVarError: QMap not defined
```
Is there already a solution for this problem?

**Comment by barche** [comment]
I have merged the Qt6 changes to main, is that what you are trying to use? If so, you also need to add the test registry (Intel Mac JLL only):

```
registry add https://github.com/barche/CxxWrapTestRegistry.git
```

**Comment by jheinen** [comment]
> I have merged the Qt6 changes to main, is that what you are trying to use? If so, you also need to add the test registry (Intel Mac JLL only):

Yes - but I tried it on an `arm64` Mac.

**Comment by jheinen** [comment]
The actual problem has been solved in the meantime - thank you very much. There is just the thing that both Qt5 and Qt6 are loaded. Maybe I should limit GR to Qt6.
