### ISSUE TITLE
Pkg.build("QML") fails with  error: ‘class cxx_wrap::ArrayRef<unsigned char>’ has no member named ‘size’

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#16]
julia> Pkg.build("QML")
Running .juliarc.jl
INFO: Building CxxWrap
INFO: Building QML
INFO: Recompiling stale cache file /home/ufechner/.julia/lib/v0.4/CxxWrap.ji for module CxxWrap.
INFO: Attempting to Create directory /home/ufechner/.julia/v0.4/QML/deps/builds/qmlwrap
INFO: Changing Directory to /home/ufechner/.julia/v0.4/QML/deps/builds/qmlwrap
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ufechner/.julia/v0.4/QML/deps/builds/qmlwrap
Scanning dependencies of target qmlwrap_automoc
[ 12%] Automatic moc for target qmlwrap
Generating moc_julia_api.cpp
Generating moc_julia_display.cpp
Generating moc_julia_object.cpp
Generating moc_julia_signals.cpp
[ 12%] Built target qmlwrap_automoc
Scanning dependencies of target qmlwrap
[ 25%] Building CXX object CMakeFiles/qmlwrap.dir/julia_api.cpp.o
[ 37%] Building CXX object CMakeFiles/qmlwrap.dir/julia_display.cpp.o
/home/ufechner/.julia/v0.4/QML/deps/src/qmlwrap/julia_display.cpp: In member function ‘void qmlwrap::JuliaDisplay::load_png(cxx_wrap::ArrayRef<unsigned char>)’:
/home/ufechner/.julia/v0.4/QML/deps/src/qmlwrap/julia_display.cpp:23:47: error: ‘class cxx_wrap::ArrayRef<unsigned char>’ has no member named ‘size’
   if(!m_pixmap.loadFromData(data.data(), data.size(), "PNG"))
                                               ^
make[2]: *** [CMakeFiles/qmlwrap.dir/julia_display.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/qmlwrap.dir/all] Fehler 2
make: *** [all] Fehler 2

Any idea?

**Comment by barche** [comment]
Yep, you need to checkout the latest CxxWrap and rebuild (after removing the usr dir in the CxxWrap deps dir).

I'll try to do a new release for CxxWrap soon, but I'd like to sort out the build issue so you don't need to manually remove the usr dir first.

**Comment by ufechner7** [comment]
Is there a separate issue in CxxWrap about automatically removing the usr dir ?

**Comment by barche** [comment]
It's not needed: CxxWrap now removes the library (not the dir, you never know if someone put a file there) so cmake should always run when you do Pkg.build("CxxWrap") now. I still have some trouble on Windows, where I would like it to download binaries if CMake or Visual Studio is not installed (see https://github.com/JuliaLang/BinDeps.jl/issues/210)

**Comment by ufechner7** [comment]
Than this issue is obsolete. Thanks a lot!
