### ISSUE TITLE
ArgumentError: TestImages not found in path

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#17]
I tried the newest version.

This time I get a different error while running Pkg.test("QML"):

julia> Pkg.test("QML")
INFO: Testing QML
Running .juliarc.jl
Button was pressed 0 times
Background counter now at 0
qt_prefix_path() = "/home/ufechner/Qt/5.5/gcc_64"
ERROR: LoadError: LoadError: ArgumentError: TestImages not found in path
 in require at ./loading.jl:233
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/ufechner/.julia/v0.4/QML/test/image.jl, in expression starting on line 3
while loading /home/ufechner/.julia/v0.4/QML/test/runtests.jl, in expression starting on line 7
=================================[ ERROR: QML ]=================================

failed process: Process(`/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/ufechner/.julia/v0.4/QML/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: QML had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71

julia> 

Any idea?

**Comment by barche** [comment]
Ah, yes, running the image test requires adding the [TestImages](https://github.com/timholy/TestImages.jl) package first. I'm not sure how to test for the availability of a package, but I should probably do that for this test.

**Comment by tbreloff** [comment]
You can either add the package to `test/REQUIRE` which only adds those packages for testing, or you could wrap `Pkg.installed(...)` in a try block:

```julia
try
    Pkg.installed("TestImages")
    # do your tests
end
```

**Comment by ufechner7** [comment]
Ok, I did:
Pkg.install("TestImages")

Now I get a new error:
WARNING: FileIO.NotInstalledError(:ImageMagick,"")
 in checked_import at /home/ufechner/.julia/v0.4/FileIO/src/loadsave.jl:12
 in load at /home/ufechner/.julia/v0.4/FileIO/src/loadsave.jl:79
 in load at /home/ufechner/.julia/v0.4/FileIO/src/loadsave.jl:42
 in testimage at /home/ufechner/.julia/v0.4/TestImages/src/TestImages.jl:22
 in test_display at /home/ufechner/.julia/v0.4/QML/test/image.jl:6
Library ImageMagick is not installed but can load format: FileIO.File{FileIO.DataFormat{:TIFF}}("/home/ufechner/.julia/v0.4/TestImages/images/lena_color_256.tif")
Exception in Julia callback  "test_display" :  "NotInstalledError"

But the Ubuntu package imagemagick is installed. Any idea?

**Comment by barche** [comment]
Pkg.add("ImageMagick"), it's complaining about the Julia ImageMagick wrappers. As an aside, the whole point of the test is to test PNG display, maybe there is a way requiring less dependencies?

**Comment by ufechner7** [comment]
Should be fixed now.
