### ISSUE TITLE
Please add QML.jl to metadata.

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#19]
I think, QML.jl has stabilized and should be added to metadata. It would be useful to have a tagged, stable release. :)

**Comment by barche** [comment]
OK, I'd like to fix some Windows installation troubles first, though. I'm also a bit busy on other work, so it'll have to wait a few days also.

**Comment by ufechner7** [comment]
Any updates on this?

**Comment by barche** [comment]
Almost there, tests on Appveyor and Travis are passing, just need to add some lines to `build.jl` to install Qt automatically on  Linux and macOS if not available.

**Comment by barche** [comment]
Done :)
