### ISSUE TITLE
Error runing tests

### ISSUE THREAD

**Issue by joa-quim** [barche/QML.jl#20]
```
INFO: Testing QML
ERROR: LoadError: LoadError: LoadError: could not load library "C:\j\.julia\v0.4\QML\deps\usr\lib\qmlwrap"
The specified module could not be found.
```
and indeed, in "C:\j\.julia\v0.4\QML\deps\usr\lib" what have is a qmlwrap.lib instead of a qmlwrap.dll

**Comment by barche** [comment]
Hi,

Could you elaborate a bit what you did to get there? Did you use the binaries (defaullt when downloading) or did you compile? Usually the problem is some dependent DLL is not installed, this may be due to the latest vcredist not being installed, for example.

**Comment by joa-quim** [comment]
Hi, what I did was (before I followed, some weeks ago, your instructions to install the QML.jl)
```
julia> Pkg.test("QML")
INFO: Computing test dependencies for QML...
INFO: Installing TestImages v0.1.1
INFO: Installing ZipFile v0.2.6
INFO: Building TestImages
INFO: Testing QML
ERROR: LoadError: LoadError: LoadError: could not load library "C:\j\.julia\v0.4\QML\deps\usr\lib\qmlwrap"
The specified module could not be found.
```
I normally know how to investigate those missing/broke dependencies and that is why I pointed to the suspicious fact, mentioned above, that I only have a qmlwrap.lib and not a qmlwrap.dll as it should

**Comment by barche** [comment]
OK, it may be that the version is too old. Normally the latest QML.jl should attempt to download binaries from here: https://github.com/barche/QML.jl/releases/tag/v0.1.0

Could you try Pkg.checkout("QML") and then Pkg.build("QML")? If that doesn't solve it, the lib dir contains a vcredist.exe that installs the required Visual Studio libs.

Note that I have only tested the binaries on my development machine, so there is a very real chance they won't work because of some forgotten dependency.

**Comment by joa-quim** [comment]
Nope. I also have all redistributables  installed (there is no escape when we install VSs).
It's clearly a problem with the qmlwrap. I don't have such. Is it a stand-alone product?
```
INFO: Attempting to Create directory C:\j\.julia\v0.4\QML\deps\downloads
INFO: Directory C:\j\.julia\v0.4\QML\deps\downloads already created
INFO: Downloading file https://github.com/barche/QML.jl/releases/download/v0.1.0/QML-julia-0.4-win64.zip
INFO: Done downloading file https://github.com/barche/QML.jl/releases/download/v0.1.0/QML-julia-0.4-win64.zip
INFO: Attempting to Create directory C:\j\.julia\v0.4\QML
INFO: Directory C:\j\.julia\v0.4\QML already created
INFO: Path C:\j\.julia\v0.4\QML\deps\usr already created
=================================[ ERROR: QML ]=================================

LoadError: Provider BinDeps.Binaries failed to satisfy dependency qmlwrap
while loading C:\j\.julia\v0.4\QML\deps\build.jl, in expression starting on line 70
```

**Comment by barche** [comment]
Ah, my bad. I botched the way to re-run cmake automatically. As a short-term fix, you can comment the lines that remove the libraries before building in CxxWrap here:
https://github.com/barche/CxxWrap.jl/blob/master/deps/build.jl#L10
And in QML.jl here:
https://github.com/barche/QML.jl/blob/master/deps/build.jl#L11

After that, remove the `deps\usr` dir in both the CxxWrap and QML package dir, and then run `Pkg.build("QML")`

I intend to fix this properly by submitting a CMake provider to BinDeps.jl, so the removal of the lib is not needed to trigger a rebuild.

**Comment by joa-quim** [comment]
Thanks, that worked.
