### ISSUE TITLE
directions for Win build are unclear

### ISSUE THREAD

**Issue by JeffreySarnoff** [barche/QML.jl#21]
The two lines that are indicated to be commented out are not right (off by 1?)

**Comment by barche** [comment]
Sorry, the instructions are out of date, you should now set the `BUILD_ON_WINDOWS` environment variable to "1" before building.

**Comment by barche** [comment]
Additionally, it seems the windows build was broken, this is fixed by commit 1db61dcf2018bad539fec6b582e1ef4c5224323d.
