### ISSUE TITLE
Installing from 0.5 fails

### ISSUE THREAD

**Issue by joa-quim** [barche/QML.jl#22]
Because its looking for a `QML-julia-0.5-win64.zip` that does not exist. Only a `QML-julia-0.4-win64.zip`

```
INFO: Building QML
INFO: Attempting to Create directory C:\j\.julia\v0.5\QML\deps\downloads
INFO: Directory C:\j\.julia\v0.5\QML\deps\downloads already created
INFO: Downloading file https://github.com/barche/QML.jl/releases/download/v0.1.0/QML-julia-0.5-win64.zip
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: The connection was closed unexpectedly."
At line:1 char:1
+ (new-object net.webclient).DownloadFile("https://github.com/barche/QM ...
+ 
```

**Comment by barche** [comment]
Ah, yes, the binaries are just a test, they are outdated. I'm slowly working towards a release, but if you want to try now installing the latest free Visual Studio, Qt and CMake and then setting the `BUILD_ON_WINDOWS` environment variable to `"1"` as well as `CMAKE_PREFIX_PATH` to the correct Qt binary dir should result in a build in a relatively painless manner.

**Comment by joa-quim** [comment]
Hmm, I have VS2015 Update 2, which I use to build other (cmake) projects but got this error that I'm not sure how to interpret.

```
INFO: Building QML
INFO: Attempting to Create directory C:\j\.julia\v0.5\QML\deps\builds\qmlwrap
INFO: Changing Directory to C:\j\.julia\v0.5\QML\deps\builds\qmlwrap
====================================================================[ ERROR: QML ]====================================================================

LoadError: could not spawn `cmake -G 'Visual Studio 14 2015 Win64' '-DCMAKE_INSTALL_PREFIX=C:\j\.julia\v0.5\QML\deps\usr' -DCMAKE_BUILD_TYPE=Release '-DCxxWrap_DIR=C:\j\.julia\v0.5\CxxWrap\deps\usr\lib\cmake' -DLIBDIR_SUFFIX= 'C:\j\.julia\v0.5\QML\deps\src\qmlwrap'`: no such file or directory (ENOENT)
```

**Comment by barche** [comment]
I think this is because cmake is not found in the path, you need to add the directory containing cmake.exe to the PATH environment variable (properties on Computer, then advanced settings)

**Comment by joa-quim** [comment]
Thanks, that part was it (I don't have cmake in the path by default).
But it seams that a bit of your data is leaking into the cmake scripts

```
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "CxxWrap::cxx_wrap" includes non-existent path

    "C:/Users/bartj/AppData/Local/Julia-0.5.0-win64/include/julia"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.
```

**Comment by barche** [comment]
I think that is because it is using the CxxWrap binaries. You could just try Pkg.build("CxxWrap") after setting `BUILD_ON_WINDOWS`, or if that doesn't work first remove the usr and downloads dirs in `.julia/0.5/CxxWrap/deps`and then try to build CxxWrap again.

**Comment by joa-quim** [comment]
Yep, that worked (had to remove the CxxWrap ``usr``. Thanks
And BTW, the build process should remove the build dirs at the end for not leaving them as forgotten trash.

**Comment by joa-quim** [comment]
Not exactly the same issue but this kills julia itself

```
julia> include("C:/j/.julia/v0.5/QML/example/glvisualize.jl")
SetProcessDpiAwareness(2) failed: COM error 0xffffffff80070005  (Unknown error 0x0ffffffff80070005), using 2

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x64fd3088 -- ptrhash_peek_bp_r at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/support\ptrhash.c:26 [inlined]
ptrhash_get_r at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/support\ptrhash.c:26 [inlined]
ptrhash_get at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src/support\ptrhash.c:26
while loading C:\j\.julia\v0.5\QML\example\glvisualize.jl, in expression starting on line 56
Press any key to continue . . .
```

**Comment by barche** [comment]
That's the most experimental example, only tested on my macOS machine. You need the latest GLVisualize release (not checked out) and add a `set_root_screen` function there, as described here: https://github.com/JuliaGL/GLVisualize.jl/issues/94#issuecomment-250417126

The error you get looks more fundamental, however, I'll have to test on Windows too. Also, I need to clean up the requirements (make them conditional somehow), so for anything to work right now all the packages listed here need to be installed, even though they are only used in the GLvisualize example:
https://github.com/barche/QML.jl/blob/master/src/glvisualize_callbacks.jl#L1-L10

The last version I tested on Windows is 1db61dcf2018bad539fec6b582e1ef4c5224323d, reverting to that should also work.

**Comment by joa-quim** [comment]
I have it all but the ``set_root_screen`` function.
