### ISSUE TITLE
accessing properties in Julia from QML

### ISSUE THREAD

**Issue by Ph0non** [barche/QML.jl#25]
I'm fairly new to gui programming and really miss something.

E.g. there is a QML element
```
Text {
            id: text1
            x: 179
            y: 155
            text: qsTr("Hello World!")
            font.pixelSize: 12
        }
```
How do I get or change the property `text`? Something like
```
@qmlget qmlcontext().text1.text
```

didn't work and it seems I miss some fundamental concept (and would expand the readme / a tutorial)

**Comment by barche** [comment]
Getting the text from Julia can either be done using a context property or a function, Julia code:
```julia
fromcontext = "From context property"
fromfunction() = "From function call"
@qmlfunction fromfunction

# All qmlapp arguments after the QML file path are interpreted as context properties with the same name
@qmlapp qmlfile fromcontext
exec()
```

QML text items:
```qml
Text {
      text: fromcontext
}
Text {
      text: Julia.fromfunction()
}
```

I have added the complete examples in `example/text.jl`.

Directly accessing the QML tree is not exposed in Julia, even though I could wrap the C++ interface to make it possible. It is however against QML usage guidelines, see the warning here:
http://doc.qt.io/qt-5/qtqml-cppintegration-interactqmlfromcpp.html#accessing-loaded-qml-objects-by-object-name

**Comment by Ph0non** [comment]
Thank you very much.

Reading the warning I understand that QML needs a different approach than C++.
