### ISSUE TITLE
error: call of overloaded ‘QVariant(long int)’ is ambiguous

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#3]
Hello,

this morning I get the following error:

(I already deleted cppwrapper and qml.jl and tried to reinstall them. The cppwrapper tests pass.)

INFO: Changing Directory to /home/ufechner/.julia/v0.4/QML/deps/builds/qml_wrapper
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ufechner/.julia/v0.4/QML/deps/builds/qml_wrapper
Scanning dependencies of target qml_wrapper_automoc
[ 33%] Automatic moc for target qml_wrapper
Generating moc_wrap_qml.cpp
[ 33%] Built target qml_wrapper_automoc
Scanning dependencies of target qml_wrapper
[ 66%] Building CXX object CMakeFiles/qml_wrapper.dir/wrap_qml.cpp.o
/home/ufechner/.julia/v0.4/QML/deps/src/qml_wrapper/wrap_qml.cpp: In instantiation of ‘QVariant qml_wrapper::detail::convert_to_qt(jl_value_t*) [with CppT = long int; jl_value_t = _jl_value_t]’:
/home/ufechner/.julia/v0.4/QML/deps/src/qml_wrapper/wrap_qml.cpp:30:50:   required from ‘QVariant qml_wrapper::detail::try_convert_to_qt(jl_value_t*) [with TypesT = {double, long int, const char*}; jl_value_t = _jl_value_t]’
/home/ufechner/.julia/v0.4/QML/deps/src/qml_wrapper/wrap_qml.cpp:42:61:   required from here
/home/ufechner/.julia/v0.4/QML/deps/src/qml_wrapper/wrap_qml.cpp:20:59: error: call of overloaded ‘QVariant(long int)’ is ambiguous
       return QVariant(cpp_wrapper::convert_to_cpp<CppT>(v));
                                                           ^
/home/ufechner/.julia/v0.4/QML/deps/src/qml_wrapper/wrap_qml.cpp:20:59: note: candidates are:
In file included from /home/ufechner/Qt/5.5/gcc_64/include/QtCore/qlocale.h:37:0,
                 from /home/ufechner/Qt/5.5/gcc_64/include/QtGui/qguiapplication.h:40,
                 from /home/ufechner/Qt/5.5/gcc_64/include/QtWidgets/qapplication.h:45,
                 from /home/ufechner/Qt/5.5/gcc_64/include/QtWidgets/QApplication:1,
                 from /home/ufechner/.julia/v0.4/QML/deps/src/qml_wrapper/wrap_qml.cpp:3:
/home/ufechner/Qt/5.5/gcc_64/include/QtCore/qvariant.h:482:5: note: QVariant::QVariant(Qt::CursorShape) <near match>
     QVariant(Qt::CursorShape) Q_DECL_EQ_DELETE;

**Comment by barche** [comment]
OK, seems Clang was more forgiving than GCC here, I got the same on Linux. Should be fixed now.

**Comment by ufechner7** [comment]
Thanks for the quick fix!
Uwe
