### ISSUE TITLE
How to deploy applications with QML?

### ISSUE THREAD

**Issue by Ph0non** [barche/QML.jl#30]
An Application with Julia + QML is finished. What parts of Qt do I need to deploy the application on a seperate (e.g.) Windows System?

Is a whole Installation of the Qt Framework necessary or do I need only some dll?

**Comment by barche** [comment]
On Windows, `Pkg.add("QML")` should download binaries for CxxWrap and QML that include all that is required for QML applications to run (it's a zip file a little under 40 MB). Note that the released binaries don't have the MSVC redistributable libraries. These can be installed separately and depending on the outcome of [this discussion](https://discourse.julialang.org/t/windows-c-binary-compatibility-mingw-vs-msvc/1250) will be included in the next release.

**Comment by Ph0non** [comment]
I run into a problem to deploy my application for windows machines. `Pkg.build("QML")` fails with 
```
LoadError: Provider BinDeps.Binaries failed to satisfy dependency qmlwrap
```
in build.jl @ line 145.

Is it a matter of 
> Note that the released binaries don't have the MSVC redistributable libraries.

?

**Comment by barche** [comment]
It could be, yes, this is the error that appears when a required dll is not found. Note that the v0.2.0 CxxWrap release also has the wrong URL for the binaries, I submitted a new tag just now but until that gets through the build.jl needs an extra `v` as shown here:
https://github.com/JuliaInterop/CxxWrap.jl/commit/381467ecf3d2b88023c71ab48d34c98ae8b75d60

I intend to do some more testing on a "clean" Windows machine soon and then tag a new QML release once this is cleared up.

**Comment by Ph0non** [comment]
I found also the missing `v` and corrected it in my local `build.jl`. Also CxxWrap builds fine on Windows.

**Comment by barche** [comment]
Sorry, didn't see the edit, I'll have to look into the columns problem, I don't have the answer off the top of my hat :)

In the mean time, I tested the following on a clean Win10 Virtualbox and it seems to work (making sure there are no old CxxWrap and QML versions around first):
```
Pkg.add("CxxWrap") # Should install v0.2.1
Pkg.clone("QML")
Pkg.build("QML") # Should download working binaries for the unreleased master
```
Does that also work for you? If so, I could tag a new QML.jl version.

**Comment by Ph0non** [comment]
I will try it at Monday at work. The ListModels update, if i close the respective window and open it (two times) again. `removeColumn` works via JuliaSignals, but the recreated Model (inside the function like in your example) with `addrole` didn't have any new columns displayed in the tableview (which are added to the ListModel). If necessary, i can provide you the full sorcecode for the application.

**Comment by Ph0non** [comment]
It works!

**Comment by barche** [comment]
I have updated the ListModel to allow removing and modifying roles, for the changes to QML see:
https://github.com/barche/QML.jl/blob/master/example/qml/tableview.qml#L49-L71

The relevant Julia changes:
https://github.com/barche/QML.jl/blob/master/example/tableview.jl#L19-L52

**Comment by Ph0non** [comment]
The example works fine, but I have still some problem to get working code for my project.

The QML part:
```
TableView {
    id: view
    Layout.alignment: Qt.AlignLeft | Qt.AlignTop
    model: nuclidesModel

    function update_columns() {
        var savedModel = model;
        model = null; // avoid model updates during reset
        while(columnCount != 0) { // remove existing columns first
            removeColumn(0);
        }
        addColumn(columnComponent.createObject(view, { "role": "name", "title": "Nuklid", "width": 100 }));
        for(var i=0; i<years.length; i++) {
            var role = years[i]
            addColumn(columnComponent.createObject(view, { "role": role, "title": role}))
        }
        model = savedModel;
    }

    // update on role change
    Connections {
        target: nuclidesModel
        onRolesChanged: view.update_columns()
    }

//                        resources:
//                        {
//                            var columns = []
//                            columns.push(columnComponent.createObject(view, { "role": "name", "title": "Nuklid", "width": 100 }))
//                            for(var i=0; i<years.length; i++)
//                            {
//                                var role  = years[i]
//                                columns.push(columnComponent.createObject(view, { "role": role, "title": role}))
//                            }
//                            return columns
//                        }

    // first time init
    Component.onCompleted: update_columns()
}
```

The Julia part:
```
# some initial values 
years = map(x -> string(x), get_years()[1:end-1]) # exposed as context property
nuclides = [Nuclide(name, zeros(length(years))) for name in ["Co60", "Cs137", "Fe55", "Ni63", "Sr90", "Am241"]]
nuclidesModel = ListModel(nuclides)

function start_nv_calc()
  # exposed as context property
  years = map(x -> string(x), get_years()[1:end-1])
  @qmlset qmlcontext().years = years

  global nv_NamedArray = get_nv() # get calculated values as NamedArray
  global nuclides = [Nuclide(name, nv_NamedArray[name,:].array) for name in names(nv_NamedArray)[1] ]
  global nuclidesModel = ListModel(nuclides)

  # add year roles manually:
  for (i,year) in enumerate(years)
    addrole(nuclidesModel, year, n -> round(n.values[i],2))
  end
  @qmlset qmlcontext().nuclidesModel = nuclidesModel

  nothing
end
@qmlfunction start_nv_calc
```

E.g. the `append_year()` function works fine and adds columns with random values. But after i called `start_nv_calc()` no values are updated. Even no columns are added (except i call `view.update_columns()` seperately with `start_nv_calc()` together). Calling `append_year()` adds columns but also with no values.

**Comment by barche** [comment]
I'm not sure if this is the problem, but could you try without the line
```
@qmlset qmlcontext().nuclidesModel = nuclidesModel
```
?

**Comment by Ph0non** [comment]
Didn't help either.

**Comment by barche** [comment]
OK, could you post a complete example that exhibits the problem? I tried to provoke the same error in the tableview example, but didn't get the failure.

**Comment by Ph0non** [comment]
https://github.com/Ph0non/NuclideVector/tree/QML

Run file `qtnv2.jl`. The code need some cleaning, but works so far.

**Comment by Ph0non** [comment]
fixed =)
