### ISSUE TITLE
Problem with window size on HighDPI displays

### ISSUE THREAD

**Issue by jheinen** [barche/QML.jl#31]
How can I easily obtain the devicePixelRatio from QML?

```qml
import QtQuick 2.0
import QtQuick.Window 2.2

ApplicationWindow {
        ... Screen.devicePixelRatio    // <== need this in Julia
    }
}
```

**Background**: when using QML + GR, the value for `painter->device()->devicePixelRatio()`, which is needed in the GR Qt driver, is always 1, even on Retina displays. This is probably due to the fact, a `CoreProfile` is selected  for the `QSurfaceFormat` in QML's application manager. OpenGL always uses raster graphics (http://doc.qt.io/qt-5/highdpi.html).

However, the value that can be obtained within QML is correct. Is there something like a `get_property()` function to access that value from Julia?

**Comment by barche** [comment]
To directly get the value from QML, you can use a context property:
https://github.com/barche/QML.jl/blob/80bb8726210bd3f2665df8fa4a07b83db05c3a12/example/gr.jl#L15-L19
Used in QML like this:
https://github.com/barche/QML.jl/blob/80bb8726210bd3f2665df8fa4a07b83db05c3a12/example/qml/gr.qml#L13-L15

However, I think that it is better to just add the `JuliaPaintedItem` object as extra parameter to the callback, this allows you to get the window and then the pixel ratio:
https://github.com/barche/QML.jl/blob/80bb8726210bd3f2665df8fa4a07b83db05c3a12/example/gr.jl#L23

I hope this one is correct, I have no retina displays so everything is 1 here :)

**Comment by jheinen** [comment]
The `JuliaPaintedItem` method works perfect - thanks a lot !!
