### ISSUE TITLE
macOS Homebrew QT version error

### ISSUE THREAD

**Issue by samuelpowell** [barche/QML.jl#37]
I get the following error when building `QML.jl`

```
LoadError: SystemError: opening file /Users/spowell/.julia/v0.5/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-core/Formula/qt5.rb: No such file or directory
```

Indeed, the only formulae available are `qt.rb`, `qt@5.5.rb`, and `qt@5.7.rb`, where the former refers to version 5.8. If I modify `build.jl` to ask Homebrew for `qt`, rather than `qt5`, the build works fine and all tests pass on 0.5.1. 

Is this a problem with my local configuration, or is a PR required due to changes in Homebrew?

**Comment by barche** [comment]
Yes, you're right, homebrew recently renamed it:
https://github.com/Homebrew/homebrew-core/pull/8334

Feel free to make a PR, this should indeed be fixed in build.jl
