### ISSUE TITLE
Testing fails, if .julia.rc changes the current directory

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#4]
My .julia.rc file contains:
```
cd("/home/ufechner/00PythonSoftware/FastSim")
push!(LOAD_PATH, pwd())
```
As a result, the following command fails:
```
julia> Pkg.test("QML")
INFO: Testing QML
Running .juliarc.jl
QQmlApplicationEngine failed to load component 
file:///mnt/ssd/ufechner/00PythonSoftware/FastSim/main.qml:-1 File not found
```
There must be a way to avoid this problem, but I could not find the solution yet.

Uwe

**Comment by barche** [comment]
OK, I've set the test to take the absolute path for the QML file, that should hopefully fix this.

**Comment by ufechner7** [comment]
Thanks a lot! This fixed the issue for me.
