### ISSUE TITLE
Incompatible Julia vs QML filepath

### ISSUE THREAD

**Issue by piever** [barche/QML.jl#45]
More of a feature request than an issue. I'm trying to add a file dialog chooser to a qml app in julia and I encounter the following issue: QML can only give me the `fileDialog.fileUrl` which looks sth like:
`file:///Users/...`

It is a bit annoying to convert it to a Julia accepted filepath (as far as I understand I would need to remove `file://` with 2 slashes for Mac OS and Linux and to remove `file:///` with 3 slashes for it to work on Windows). It'd be nice to have a platform independent way to pass from one to the other.

**Comment by barche** [comment]
It should just return the local path now. Maybe someday we'll run into trouble when someone wants to use a real URL, but we'll deal with it when that happens.

**Comment by piever** [comment]
Thanks for fixing this!

I have one Off Topic questions, I hope you don't mind if I ask it here: I'm developing a small package to simplify making statistical plots. It's basically a GUI that can load data and output plots from StatPlots.jl . I've found your QML package extremely useful for this kind of application (it looks native and supports GR plots), but I'm new to QML and I'm learning a lot going through your examples. I've ended up taking and modifying snippets of code from your examples to get my package to work (simple things, like the "selectfile" dialog or the "plots" example). I wanted to ask you if that's OK (I would of course acknowledge the QML package and your code in the README).

**Comment by barche** [comment]
Sure, that's what the examples are there for, glad you find them useful :)

**Comment by piever** [comment]
One more question: do you know more or less when the next QML release is? I haven't found a way to make my package dependent on QML master so I'm unsure whether I should add some hacky way to get the thing to work now or just wait for the next QML release and add the correct dependencies.

**Comment by barche** [comment]
I'll set things in motion to do a v0.4.2 release, should be pretty quick

**Comment by barche** [comment]
It's in metadata now, do make sure to set up the version bounds like this in your own REQUIRE file:
```
QML 0.4.2 0.5-
```
This will make sure your package doesn't break when breaking changes are introduced in 0.5.

**Comment by piever** [comment]
Thanks for the heads-up!
