### ISSUE TITLE
Calling unexported functions from QML

### ISSUE THREAD

**Issue by piever** [barche/QML.jl#47]
I'm having issues calling an unexported function from QML.
I have defined a function `my_function` in a module called PlugAndPlot.

I've tried both (I guess they are the same):

`@qmlfunction PlugAndPlot.my_function`

or

`@qmlfunction my_function`

and now in QML `Julia.my_function` thinks that `my_function` is undefined, whereas `Julia.PlugAndPlot.my_function` throws:

`TypeError: Cannot call method 'my_function' of undefined `

Is there a workaround other than exporting `my_function`?

**Comment by barche** [comment]
I think if you do
```julia
my_function = PlugAndPlot.my_function
```
before the macro call, it should work. However, this issue made me realize the whole function call mechanism was still based around passing around only the name of a function. In the latest master the function object is used directly, so you can now do:

```julia
qmlfunction("my_function", PlugAndPlot.my_function)
```

**Comment by piever** [comment]
Thanks, the new function form works beautifully! I was also about to run into the issue about the function name with a `!` character, glad that one also got fixed.
