### ISSUE TITLE
exec() doesn't exit after QML error that prevents window from being displayed

### ISSUE THREAD

**Issue by ancapdev** [barche/QML.jl#49]
First, thanks for a very useful package, it's helped me start building some GUI apps in Julia with minimal effort.

If there's an error in the QML that prevents the application window from being rendered, there's no way to close it, and exec() doesn't exit. I deal with this by stopping and starting Julia, which has some associated startup cost. Is there a better way to handle this, or have I missed something?

**Comment by barche** [comment]
Thanks, minimal effort is the objective ;)

I was convinced I had this fixed here:
https://github.com/barche/QML.jl/commit/3b58295154fb2ce810d0db5fc38cb1cd9d078782

Do you have a simple example that produces this behavior? You're on the latest release, right?

**Comment by ancapdev** [comment]
I'm on 0.4.3, which I think is the latest, and this is enough to reproduce:

```Js
import QtQuick 2.7
import QtQuick.Controls 1.5

ApplicationWindow {
    visible: true
    fail
}
```

```Julia
using QML
@qmlapp "C:/temp/fail.qml"
exec()
```

Outputting:
```
Warning: QQmlApplicationEngine failed to load component ((null):0, (null))
Warning: file:///C:/temp/fail.qml:7 Syntax error
 ((null):0, (null))
```

Then it hangs on the ```exec()```.

Julia version:
```
Julia Version 0.5.2
Commit f4c6c9d (2017-05-06 16:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)
```

Running this from Atom, if that makes any difference, using the JuliaPro 0.5.2.2 release with few package changes.

**Comment by barche** [comment]
Ah, yes, it used to be even worse, with a hang on the `@qmlapp` :) Should be better now, the parse error will raise an error instead of just returning false, so the `exec` is never reached.

**Comment by ancapdev** [comment]
Thanks
