### ISSUE TITLE
Update to Julia v0.7 or v1.0

### ISSUE THREAD

**Issue by Ph0non** [barche/QML.jl#57]
Are there plans to update this package to the latest Version of Julia?

E.g. for the [build.jl](https://github.com/barche/QML.jl/blob/master/deps/build.jl)  the function to determine the OS changed:

```•The operating system identification functions: is_linux, is_bsd, is_apple, is_unix, and is_windows, have been deprecated in favor of Sys.islinux, Sys.isbsd, Sys.isapple, Sys.isunix, and Sys.iswindows, respectively ```

**Comment by barche** [comment]
I have it mostly working on my computer, I should clean things up and submit a PR. The main issue still to resolve is the installation of Qt itself, but I suppose I could do an intermediate release where the user has to do this himself.

**Comment by maximilianpreisinger** [comment]
That would be awesome!

**Comment by barche** [comment]
OK, I have committed what works for me to the master branch, see the [README](https://github.com/barche/QML.jl#installation) on how to install this. Note that this requires building [JlQML](
https://github.com/barche/jlqml) manually for now.

Before making a release, I will have to look into building the binaries using BinaryBuilder, the main challenge for that is getting a compatible Qt built.

**Comment by xandhu** [comment]
Which toolset should Qt be built with on Windows? I have tried using pre-built binaries from https://www.qt.io/offline-installers, the mingw73_64 version to be more specific, and I could build JLQML with mingw-w64 however when pre-compiling QML I get an error when trying to [wrap libjlqml](https://github.com/barche/QML.jl/blob/master/src/QML.jl#L34): 
`ERROR: Symbol for type QVariant was not found. A Value of type null was found instead. Searched modules: Main Main Base CxxWrap Base`

I'm assuming that means I'm using the wrong Qt libraries.

**Comment by barche** [comment]
Currently, this is easiest with the Visual Studio binaries, but it requires building libcxxwrap-julia (the CxxWrap binaries) and jlqml using Visual Studio. There is a bit more info here: https://discourse.julialang.org/t/linker-error-with-cxxwrap-on-windows10/19967/2?u=barche

But I urgently need to streamline this :)

**Comment by aminya** [comment]
Is Julia 1.1.1 supported now? The documentation is not clear. https://github.com/barche/QML.jl#installation

**Comment by barche** [comment]
It should on master, see issue #61 for more complete instructions.

**Comment by ufechner7** [comment]
Can this issue be closed?

**Comment by barche** [comment]
Yep!
