### ISSUE TITLE
Update dependencies (CxxWrap)

### ISSUE THREAD

**Issue by maximilianpreisinger** [barche/QML.jl#58]
The project currently doesn't build under julia 0.7 because of CxxWrap. QML uses an old version of it (0.5.0), which does not compile. The newest version of CxxWrap (0.7.4) does compile under julia 0.7. Is it possible to change the dependency such that both packages compile?

**Comment by barche** [comment]
Yes, still working on it, this is part of issue #57, so I'm closing this one.
