### ISSUE TITLE
Future of QML

### ISSUE THREAD

**Issue by diam** [barche/QML.jl#60]
Bonjour,

I tried to install QML on the last Julia version.

<pre>
julia --version
# => julia version 1.1.0

julia -e 'using Pkg; pkg"add QML"'
# => 
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package QML [2db162a6]:
 QML [2db162a6] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.3] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only 
         versions [0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.3]
 └─restricted by julia compatibility requirements to versions: 
         uninstalled — no versions left
Stacktrace:
... (cut, I can post the full message if needed)
</pre>

My question: is this package going to be maintained for future versions of Julia?
Perhaps some core team Julia developper could help to maintain QML (I hope so!)?

Merci d'avance !
-- Maurice

**Comment by barche** [comment]
Bonjour Maurice :)

The good news is that it is not as broken as it seems, and support for Julia 1.x is already there. The bad news is that supplying binaries turned out not to be so simple using the BinaryBuilder system, so you will need to build the jlqml library from source, see also issue #57 

Meilleures salutations,

Bart

**Comment by diam** [comment]
(Sorry for my late response)
Thank you very much Bart: I was able to install and test the latest version of QML.jl thanks to the issue [#55](https://github.com/barche/QML.jl/issues/57) and with the help of the installation section of [README](https://github.com/barche/QML.jl#installation).


But my initial question about the future of QML still remains.

I know (actually, I guess ;-) that maintaining such a package for Julia is a big challenge... and a lot of work! But the stability of the toolbox for using QML with Julia and the ease of installation of the latter would be a strong argument for using it.

When we want to test a simple pyplot example, we need to install about 1GB of Python garbage in Julia! So I think it would be perfectly acceptable to include all QML dependencies in the QML.lj package if it simplifies installation and limits dependancy problems.

- Once the installation of QML.jl under Julia-1.x will be solved, will you have time to maintain QML.jl over time?
- What do you think of a sumo installation for QML.jl?

Merci d'avance !
-- Maurice

**Comment by barche** [comment]
After some more poking around, I was able to build a working Qt5 using BinaryBuilder. It will probably take a few more weeks, but an integrated cross-platform solution using supported binaries looks to be in sight.

**Comment by phlavenk** [comment]
Hi @barche ,
what is the status of the changes in the QML package? is it necessary to self-build the library in order to get QML working on Julia 1.4? What is the BB story regarding the library build? Thank you very much for an update.

**Comment by barche** [comment]
Close now, updates can be followed here: https://github.com/JuliaPackaging/Yggdrasil/pull/586

Once that is in and CxxWrap 0.1 is released, building QML binaries using BinaryBuilder should be a breeze.

**Comment by ufechner7** [comment]
Can this issue be closed? Or would you say you still need some support, if yes in which area?

**Comment by barche** [comment]
Yes, thanks for the reminders :)
