### ISSUE TITLE
Info about upcoming removal of packages in the General registry

### ISSUE THREAD

**Issue by KristofferC** [barche/QML.jl#65]
As described in https://discourse.julialang.org/t/ann-plans-for-removing-packages-that-do-not-yet-support-1-0-from-the-general-registry/ we are planning on removing packages that do not support 1.0 from the General registry. This package has been detected to not support 1.0 and is thus slated to be removed. The removal of packages from the registry will happen approximately a month after this issue is open.

To transition to the new Pkg system using `Project.toml`, see https://github.com/JuliaRegistries/Registrator.jl#transitioning-from-require-to-projecttoml.
To then tag a new version of the package, see https://github.com/JuliaRegistries/Registrator.jl#via-the-github-app.

If you believe this package has erroneously been detected as not supporting 1.0 or have any other questions, don't hesitate to discuss it here or in the thread linked at the top of this post.

**Comment by RalphAS** [comment]
@barche I recently verified that current QML master branch works on Julia v1.2 (at least for my projects and most of your examples), after carefully following all your instructions for JlQML. I understand that you'd like to have something more polished for a real release, but please don't let your promising work be shunted off to obscurity!

**Comment by barche** [comment]
Thanks for the kind words, but doing a release at this point won't help much, it will just fail the automated tests due to no binaries being available.

Also, wow, that is one month ago already :)

**Comment by ufechner7** [comment]
Well, then just disable the tests that would fail...Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Bart Janssens <notifications@github.com> 
Datum: 06.10.19  22:18  (GMT+01:00) 
An: "barche/QML.jl" <QML.jl@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: Re: [barche/QML.jl] Info about upcoming removal of packages in the
  General registry (#65) 

Thanks for the kind words, but doing a release at this point won't help much, it will just fail the automated tests due to no binaries being available.
Also, wow, that is one month ago already :)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/barche/QML.jl/issues/65?email_source=notifications\u0026email_token=ABAJ7XKEXBD3YPLBF767VFDQNJBYLA5CNFSM4ITVE2Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOTBXA#issuecomment-538783964",
"url": "https://github.com/barche/QML.jl/issues/65?email_source=notifications\u0026email_token=ABAJ7XKEXBD3YPLBF767VFDQNJBYLA5CNFSM4ITVE2Z2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOTBXA#issuecomment-538783964",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by barche** [comment]
No, this isn't about any internal QML.jl tests, if I understand correctly there is now a standard test that does Pkg.add when you register or release a new version, and that would fail since a normal Pkg.add won't work yet (is this correct @KristofferC ?)

**Comment by ufechner7** [comment]
Well, if I try to add QML to Julia 1.2 I get:
```
(v1.2) pkg> add QML
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package QML [2db162a6]:
 QML [2db162a6] log:
 ├─possible versions are: [0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.3] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0, 0.3.0-0.3.1, 0.4.0-0.4.3]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

(v1.2) pkg> 
```
But this should be easy to fix, or not?

**Comment by ufechner7** [comment]
Ok tried to add QML#master, this worked when trying twice:
```
(v1.2) pkg> add QML#master
   Cloning git-repo `https://github.com/barche/QML.jl.git`
  Updating git-repo `https://github.com/barche/QML.jl.git`
 Resolving package versions...
 Installed Showoff ────────────── v0.3.1
 Installed MappedArrays ───────── v0.2.2
 Installed AbstractFFTs ───────── v0.4.1
 Installed OffsetArrays ───────── v0.11.1
 Installed ColorVectorSpace ───── v0.7.1
 Installed GLFW ───────────────── v3.1.0
 Installed AxisAlgorithms ─────── v1.0.0
 Installed ImageFiltering ─────── v0.6.5
 Installed FFMPEG ─────────────── v0.2.3
 Installed CxxWrap ────────────── v0.8.2
 Installed ImageAxes ──────────── v0.6.1
 Installed ImageTransformations ─ v0.8.0
 Installed GLMakie ────────────── v0.0.8
 Installed Interpolations ─────── v0.12.2
 Installed AbstractPlotting ───── v0.9.10
^C   Cloning [6218d12a-5da1-5696-b52f-db25d2ecc6d1] ImageMagick from https://github.com/JuliaIO/ImageMagick.jl.git
 Installed ImageMagick ────────── v0.7.5
   Cloning [a09fc81d-aa75-5fe9-8630-4744c3626534] ImageCore from https://github.com/JuliaImages/ImageCore.jl.git
 Installed ImageCore ──────────── v0.8.5
   Cloning [4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd] FFTViews from https://github.com/JuliaArrays/FFTViews.jl.git
ERROR: failed to clone from https://github.com/JuliaArrays/FFTViews.jl.git, error: GitError(Code:ERROR, Class:SSL, SSL error: 0xffffffff - UNKNOWN ERROR CODE (0001))

(v1.2) pkg> add QML#master
  Updating git-repo `https://github.com/barche/QML.jl.git`
 Resolving package versions...
 Installed FFTW ───────── v1.0.1
 Installed SimpleTraits ─ v0.9.1
 Installed FFTViews ───── v0.3.0
  Updating `~/.julia/environments/v1.2/Project.toml`
  [2db162a6] + QML v0.5.0 #master (https://github.com/barche/QML.jl.git)
  Updating `~/.julia/environments/v1.2/Manifest.toml`
  [621f4979] + AbstractFFTs v0.4.1
  [537997a7] + AbstractPlotting v0.9.10
  [13072b0f] + AxisAlgorithms v1.0.0
  [631607c0] + CMake v1.1.2
  [aafaddc9] + CatIndices v0.2.0
  [a2cac450] + ColorBrewer v0.4.0
  [c3611d14] + ColorVectorSpace v0.7.1
  [ed09eef8] + ComputationalResources v0.3.0
  [d38c429a] + Contour v0.5.1
  [150eb455] + CoordinateTransformations v0.5.0
  [dc8bdbbb] + CustomUnitRanges v0.2.0
  [1f15a43c] + CxxWrap v0.8.2
  [ffbed154] + DocStringExtensions v0.8.0
  [c87230d0] + FFMPEG v0.2.3
  [4f61f5a4] + FFTViews v0.3.0
  [7a1cc6ca] + FFTW v1.0.1
  [b38be410] + FreeType v2.1.1
  [663a7486] + FreeTypeAbstraction v0.4.2
  [f7f18e0c] + GLFW v3.1.0
  [e9467ef8] + GLMakie v0.0.8
  [4d00f742] + GeometryTypes v0.7.6
  [bbac6d45] + IdentityRanges v0.3.0
  [2803e5a7] + ImageAxes v0.6.1
  [a09fc81d] + ImageCore v0.8.5
  [6a3955dd] + ImageFiltering v0.6.5
  [6218d12a] + ImageMagick v0.7.5
  [02fcd773] + ImageTransformations v0.8.0
  [9b13fd28] + IndirectArrays v0.5.0
  [a98d9a8b] + Interpolations v0.12.2
  [ee78f7c6] + Makie v0.9.3
  [dbb5928d] + MappedArrays v0.2.2
  [7269a6da] + MeshIO v0.3.1
  [66fc600b] + ModernGL v1.0.0
  [510215fc] + Observables v0.2.3
  [6fe1bfb0] + OffsetArrays v0.11.1
  [19eb6ba3] + Packing v0.3.0
  [5432bcbf] + PaddedViews v0.4.2
  [995b91a9] + PlotUtils v0.5.8
  [2db162a6] + QML v0.5.0 #master (https://github.com/barche/QML.jl.git)
  [c84ed2f1] + Ratios v0.3.1
  [6038ab10] + Rotations v0.12.0
  [992d4aef] + Showoff v0.3.1
  [73760f76] + SignedDistanceFields v0.4.0
  [699a6c99] + SimpleTraits v0.9.1
  [276daf66] + SpecialFunctions v0.8.0
  [90137ffa] + StaticArrays v0.11.0
  [06e1c1a7] + TiledIteration v0.2.3
  [1cfade01] + UnicodeFun v0.4.0
  [efce3f68] + WoodburyMatrices v0.4.1
  Building FFTW → `~/.julia/packages/FFTW/MJ7kl/deps/build.log`

(v1.2) pkg> 
```
So which test do expect to fail when creating a new version from master?

**Comment by ufechner7** [comment]
Ok, precompile failed. How to fix that?

**Comment by barche** [comment]
Referring to issue #60 since this one is Julia-admin-created and closed.
