### ISSUE TITLE
Allow to use Qt.labs.settings

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#8]
Hello,
if I add the line:
```
import Qt.labs.settings 1.0
```
at the top of any .qml file I get the error message:
```
julia> include("gui.jl")
QQmlApplicationEngine failed to load component 
file:///home/ufechner/00Julia/QML.jl/example/qml/main.qml:5 module "Qt.labs.settings" is not installed
```
Being able to use this component would be very useful, because it automatically stores and restores the GUI properties.

**Comment by barche** [comment]
Seems to work here, I don't think this is a QML.jl issue, but if this is on Ubuntu you should install:
https://launchpad.net/ubuntu/utopic/+package/qml-module-qt-labs-settings

Ubuntu (or debian?) has broken Qt and QML down into a huge number of packages, it seems.

**Comment by ufechner7** [comment]
I do not want to use the QT version from Ubuntu, but the QT that is installed in:
/home/ufechner/Qt/5.5
How can I tell QML.jl to use this version?

**Comment by barche** [comment]
This is detected the first time QML.jl is built. To correct the situation, do the following:
1. delete the `builds` and `usr` dirs from `.julia/v0.4/QML/deps`
2. `export CMAKE_PREFIX_PATH=/home/ufechner/Qt/5.5`
3. Run Julia in the same terminal as the export and rebuild QML

I'm not 100% sure, but I think subsequent builds should reuse the same Qt. If not, you may need to add CMAKE_PREFIX_PATH to your profile, or set the environment variable in juliarc if that is possible.

**Comment by ufechner7** [comment]
Thanks for your suggestion. I deleted CppWrapper and QML, exported the prefix and reinstalled both. This did not solve the problem. The component is installed, because I can use it with C++ and QT Creator. Perhaps there is a different search path for QML components?

**Comment by ufechner7** [comment]
It is working now. :+1: 
I had to use the following export command:
export CMAKE_PREFIX_PATH=/home/ufechner/Qt/5.5/gcc_64

Directly under the prefix path there must be a lib directory.

But it would be nice, if the build script of QML.jl could report the prefix of the QT version that it is using (probably many people have multiple QT versions on their PC).
Furthermore it would be nice to add this info to the README.md file.

**Comment by ufechner7** [comment]
I think, this can be closed now.
