### ISSUE TITLE
Using `qmlfunction` on anonymous functions seems to cause segfaults

### ISSUE THREAD

**Issue by bramtayl** [barche/QML.jl#87]

**Comment by barche** [comment]
This could be because the function is not protected from GC. Could you run your test with `GC.enable(false)` at the start of the Julia file and see if that makes a difference? If so, this will need a change in jlqml and a new binary release.

**Comment by barche** [comment]
I had to update jlqml to fix the segfault in the nightly test, so I included the probable fix for this too.

**Comment by bramtayl** [comment]
Yup that seems to have done it! Thanks!
