### ISSUE TITLE
Passing of parameters of type integer and bool should be implemented

### ISSUE THREAD

**Issue by ufechner7** [barche/QML.jl#9]
When I pass a list of arguments to a Julia function in QML, only strings and floating point numbers seam to be supported. Not a big deal, but it would be nice if other types are supported, too.

**Comment by barche** [comment]
Should be fixed, be sure to also update CppWrapper since the actual conversion happens there.

**Comment by ufechner7** [comment]
Thanks for the quick fix.
There is one issue, though: Integer parameters are passed as Int32 to Julia, while the default integer type of Julia is Int64, at least on a 64 bit machine. This might lead to type instabilities.

**Comment by barche** [comment]
OK, but would it be wise to convert to Int64 then? I'm not sure the type instability would be a huge issue for this kind of callbacks?

**Comment by ufechner7** [comment]
No, converting is not necessary. Just mention the fact, that integers are return as Int32 in the docs.
