### ISSUE TITLE
Unsatisfiable requirements detected for package FileIO while installing in Julia 1.3.1

### ISSUE THREAD

**Issue by kantonesisch1234** [barche/QML.jl#90]
I tried to add the package in Julia 1.3.1 and received the following error message:

`ERROR: Unsatisfiable requirements detected for package FileIO [5789e2e9]:
 FileIO [5789e2e9] log:
 ├─possible versions are: [1.0.0-1.0.7, 1.1.0, 1.2.0-1.2.4, 1.3.0, 1.4.0] or uninstalled
 ├─restricted to versions 1.4.0-1 by QML [2db162a6], leaving only versions 1.4.0
 │ └─QML [2db162a6] log:
 │   ├─possible versions are: 0.5.0 or uninstalled
 │   └─QML [2db162a6] is fixed to version 0.5.0
 └─restricted to versions 1.2.1 by an explicit requirement — no versions left`

Does it imply that the package cannot be installed in Julia 1.3.1?

**Comment by barche** [comment]
That was a mistake following a suggestion by CompatHelper, should be fixed now!
