### ISSUE TITLE
[help wanted] Reading QML map of key-value pairs in Julia

### ISSUE THREAD

**Issue by a-ill** [barche/QML.jl#94]
I am trying to pass a map of key-value pairs from QML to Julia and then convert the map to Julia dictionary for further use inside Julia. The first part works just fine as well as accessing elements using keys if I specify them myself like `mymap["name"]`.  However, in order to construct a Julia dictionary I need some way to extract keys from a map, which cannot figure out how to do.
 
One way here seem to extract both keys and values on QML side and pass to a Julia function.

QML:
``` 
var mymap = {"key1": "value1", "key2": "value2"}
Julia.returnmap(Object.keys(mymap),Object.values(mymap))
```
Julia:
``` 
function returnmap(keys,values)
  dict = Dict()
  sizehint!(dict, length(keys))
  for i in 1:length(keys)
      dict[keys[i]] = values[i]
  end
end
```
However, the keys and the values in the dictionary are of the type QString, which is not ideal, because it seems that we cannot do anything with them in Julia.
```
julia> dict
Dict{Any,Any} with 2 entries:
  QVariant of type QString with value key1 => QVariant of type QString with value value1
  QVariant of type QString with value key2 => QVariant of type QString with value value2
```
Using string() does nothing to the type. However, if we use the following code, then QString does get converted to String, but I am sure it is a very inefficient way to do that
```
function string(var::QML.QVariantDereferenced)
  return String[var][1]
end
```

**Comment by barche** [comment]
The problem is that all the values from QML are wrapped in a `QVariant`. You can get the value by using the `QML.value` function, so this might work: (untested)

```julia
function returnmap(keys,values)
  dict = Dict()
  sizehint!(dict, length(keys))
  for i in 1:length(keys)
      dict[QML.value(keys[i])] = QML.value(values[i])
  end
end
```

You will now get actual `QString` values, which should work as normal Julia strings (and if not, that's a bug in QML ;)

**Comment by a-ill** [comment]
@barche That does work. Thank you!
